#!/bin/bash --login
#SBATCH --job-name=comp_n_%a
#SBATCH --array=1-25:1
#SBATCH --output=out/conj_%a.out
#SBATCH --time=168:00:00  
#SBATCH --mem=1000G
#SBATCH --mail-user=wack@math.tu-berlin.de
#SBATCH --mail-type=BEGIN,END,FAIL

export JULIA_NUM_PRECOMPILE_TASKS=1
unset LD_LIBRARY_PATH 
JULIA_DEPOT_PATH=$TMPDIR/julia julia-1.9 -e "using Pkg; Pkg.activate(\"../\",io=devnull); Pkg.instantiate(io=devnull); n=$SLURM_ARRAY_TASK_ID; include(\"./conjecture_hpc.jl\");"

